### ISSUE TITLE
Fix Terraform Cloud setup example repo docs

### ISSUE THREAD

**Issue by quixoticmonk** [aws-samples/aws-modernization-with-hashicorp-terraform#7]
The tfc-guide-example repo has been updated to remove the usage of `random` provider. This is still being referenced in the content.

## Proposed change: 

Update the documentation on Terraform Cloud setup with the updates from the [tfc-guide-example](https://github.com/hashicorp/tfc-guide-example/blob/master/main.tf) repo.

**Comment by wellsiau-aws** [comment]
thanks for your contribution!
